---
controller_credential_types:
  - name: AWS credentioals
    description: Test AWS Credential
    state: present
    inputs:
      fields:
      - type: string
        id: accesskey
        label: access key
        secret: true
      - type: string
        id: secretkey
        label: secret key
        secret: true
      required:
      - accesskey
      - secretkey
    injectors: 
      extra_vars: 
        accesskey: !unsafe "{{ accesskey }}"
        secretkey: !unsafe "{{ secretkey }}"
  - name: "controller file"
    description: "AIP Controller cli file"
    state: present  
    inputs:
      fields:
        - id: tower_cli_api_url
          type: string
          label: tower_cli API URL
        - id: tower_cli_api_token
          type: string
          label: tower_cli API token
      required:
        - tower_cli_api_url
        - tower_cli_api_token
    injectors: {
      "file": {
        "template": "[general]\nhost={{ tower_cli_api_url }}"
        },
        "extra_vars":
          "TOWER_CLI_CFG_FILE": "{ { tower.filename }}"
          "tower_cli_api_token": "{ { tower_cli_api_token }}"
      } }

