# This is a basic workflow to help you get started with Actions

name: CI
on:
  release:
    types: ["created"]
    
# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
      
      - name: print the github variables
        run: |
           echo this is githubeventname ${{ github.event_name }}
           echo this is githubreference ${{ github.ref }}
           echo this is githubrefname ${{ github.ref_name }}
           echo "Release title is: ${{ github.event.release.name }}

      - name: print the variable based on env
        run: |
          case ${{ github.event_name }} in 
            release)
              stage=${{ contains( github.ref, 'release-') && 'prod' || 'test' }}
              mode='false'
              ;;
            pull_request)
               stage=${{ contains( github.ref_name, 'main' ) && 'prod' || 'test' }}
               mode='true'
              ;;
            push)
               stage='test'
               mode='true'
              ;;
          esac
          echo this is the stage value $stage
           

